#:import menu menu
MainWidget:

<MainWidget>:
    canvas.before:
        Rectangle:
            source:'images/bg1.jpg'
            size: self.size

    menu_widget: menu_widget
    perspective_point_x: self.width/2
    perspective_point_y: self.height*3/4
    MenuWidget:
        id: menu_widget
    Label:
        text: root.score_txt
        font_size: dp(20)
        font_name:'fonts/Eurostile.ttf'
        pos_hint: {'x': 0, 'top': 1}
        size_hint: .18, .2
    